 CUDA_VISIBLE_DEVICES=0,1,2,3,4,5 python -m encoders.finetuning.train_modernbert \
    --model_name_or_path answerdotai/ModernBERT-large \
    --output_dir out/ModernBERT-large-en \
    --learning_rate 8e-5 \
    --num_train_epochs 4 \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --per_device_eval_batch_size 16 \
    --logging_steps 25 \
    --eval_steps 25 \
    --save_strategy steps \
    --load_best_model_at_end True \
    --metric_for_best_model eval_loss \
    --save_total_limit 1 \
    --eval_strategy steps 
